import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "aos/dist/aos.css";
import "./globals.css";
import AOSProvider from "./components/AOSProvider";

const k2d = K2D({
  variable: "--font-k2d",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${k2d.variable} antialiased`}>
        <AOSProvider>
          <div className="mx-auto sm:max-w-xl md:max-w-2xl lg:max-w-3xl xl:max-w-350 overflow-hidden font-k2d">
            {children}
          </div>
        </AOSProvider>
      </body>
    </html>
  );
}
